import { Lato, Open_Sans, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Navbar } from "@/components/navbar";
import { CustomScrollbar } from "@/components/custom-scrollbar";
import { Footer } from "@/components/footer";

const r = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${r.className} antialiased`}
      >
        <ThemeProvider enableSystem={true} attribute="class">
          <Navbar>
            {children}
          </Navbar>
          <Footer />
          <CustomScrollbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
